### ISSUE TITLE
Can't run on iPhone 4 (7.1.2) 

### ISSUE THREAD

**Issue by quattroGeko** [Mozharovsky/CVCalendar#7]
Hi,
i tried run cvCalendar-Demo on my iPhone 4 (7.1.2) but getting error "2015-01-14 13:07:06.278 CVCalendar Demo[479:60b] Could not load the "present-100" image referenced from a nib in the bundle with identifier "com.gameapp.production.CVCalendar-Demo"

i delete present-100 image but getting another error

fatal error: unexpectedly found nil while unwrapping an Optional value on startup
![untitled](https://cloud.githubusercontent.com/assets/7033996/5737931/2bcec5ba-9bef-11e4-8d50-481b9db731a0.png)

i set deployment target 7.1 it running on simulator but doesn't run on iPhone

Thanks

**Comment by Mozharovsky** [comment]
Hello @quattroGeko, 

Thank you for reporting this issue. The image you're experiencing a problem with has 3X resolution for being supported on iPhone 6 & Plus and the rest of iOS 8 supporting devices. iPhone 4 is not compatible with the latest iOS releases, so you have to use 1X to 2X images for your assets. 

My advice is to give a try with a similar image but with the appropriate resolution. 

I hope it helps!

**Comment by quattroGeko** [comment]
Hi Eugene,

this is really fantastic components. but i tried remove all image same error. it’s working on simulator 7.1 but cant run on iphone

thanks

**Comment by tiemevanveen** [comment]
Hi Mozharovsky,

I don't think the problem is related to image resolutions but with a result variable being nil and then force unwrapped, see my comment here: https://github.com/Mozharovsky/CVCalendar/commit/45e125cfc7d31c3b67d6a4e7ffa8db365fb7bb0b#diff-6

**Comment by tiemevanveen** [comment]
Might it have something todo with my (dutch) week starting on monday, not on sunday?

**Comment by Mozharovsky** [comment]
@quattroGeko, please let me know what system language you have. 

Hello @tiemevanveen, 

Thank you for figuring out this bug. You might be right about @quattroGeko's issue, perhaps it lies underneath the calendar math. Anyway, your issue is occurring due to the Netherland's calendar type. In the US and UK we've got Sunday as a starter weekday for a week that is a little bit different in your country.  CVCalendar is currently using the current calendar (i.e. the one specific for your system), as a result you're getting a specific calendar for the Netherlands and then Calendar Manager fails in processing math part. 

At this moment I'm working on a new way of calculating weekdays per week in a month. So new updates on CVCalendarManager are about to come pretty soon. There you'll be able to set your own starter weekday or simply use the system one. 

Regards, 
Eugene

**Comment by tiemevanveen** [comment]
Hi Eugene,

The problem is indeed caused by dutch calendar, switching my region to US 'fixes' the bug.

I was trying to fix this issue in the app but stumbled apon what seems to be a bug in NSDateComponents. I'm preparing a Stackoverflow question and a sample project to send to Apple now.

**Comment by tiemevanveen** [comment]
Stackoverflow: http://stackoverflow.com/questions/27990503/nsdatecomponents-wrong-weekday
Testproject: https://github.com/tiemevanveen/NSDateComponentsTest/tree/master

**Comment by tiemevanveen** [comment]
> At this moment I'm working on a new way of calculating weekdays per week in a month. So new updates on CVCalendarManager are about to come pretty soon. There you'll be able to set your own starter weekday or simply use the system one.

Sounds good btw!

**Comment by quattroGeko** [comment]
Hi Guys,

i changed my iPhone region to us & component running fine,thanks @Mozharovsky @tiemevanveen

**Comment by Mozharovsky** [comment]
Fixes are coming. Please guys be more respectful to the United States of America. We love our country. ;-)

**Comment by Mozharovsky** [comment]
Guys, I've just pushed a new version of CVCalendarManager to develop branch (b5faf987aea1c0e1f414b9fea16112438ead20fd). 

I've got enough of work for this day, so either you'll have to wait until I'm able to start working or you may try to fix it yourself. I added the TODO markers, it's all about little refactoring of weekdays reading logic and delegating first weekday.

**Comment by tiemevanveen** [comment]
Thanks for the fixes! I've tried to fill in your TODO's by I got stuck somewhere half way.. 

![screen shot 2015-01-17 at 00 39 02](https://cloud.githubusercontent.com/assets/1330668/5786177/466b5584-9de1-11e4-8f37-23866e10dcd0.png)

Haha

In the meantime, [my stackoverflow question](http://stackoverflow.com/questions/27990503/nsdatecomponents-returns-wrong-weekday) resulted in a possible explanation for a part of the bug. In short, you can't rely on `components.weekday` to get the day of the week for a certain day. You could use the following instead: 

    dayOfWeek = calendar.ordinalityOfUnit(.WeekdayCalendarUnit, inUnit: .WeekCalendarUnit, forDate: _date)

**Comment by Mozharovsky** [comment]
Well, the analysis works fine now. I've simply used an instance variable for storing a weekday starter. Take a look at the updated source code 0beedbe3a3cd364826df289c811e4b1109b1655c. 

And looks exactly the same I have in my iPhone with the Dutch calendar. 
![image986](https://cloud.githubusercontent.com/assets/6762769/5789162/93a4bfba-9e2d-11e4-8f67-38a9d553d0fd.png)

Now it's about adding delegating a weekday starter and CVMenuView with corresponding weekday symbols.

**Comment by tiemevanveen** [comment]
Cool! But your screenshot is still showing a calendar starting on Sunday?

I think you should also try it on a real phone and switch the region to dutch before running or installing the app. I couldn't get my simulator to show a week starting on Monday either..

Good effort though, thanks for working on this!

**Comment by Mozharovsky** [comment]
The picture above is showing the Dutch calendar. The only issue is weekday symbols showed in the menu view. Now I'm working on its delegation.

**Comment by tiemevanveen** [comment]
Ohh, yeah you're right, I focussed to much on the labels!

**Comment by Mozharovsky** [comment]
Well, I've just pushed code supporting custom starter weekday. Take a look at 6805c04bcbe2d5b06cdf8ef335886135db7ea01f. 

Here we go. 
![2015-01-17 13 41 05](https://cloud.githubusercontent.com/assets/6762769/5789936/cfea6116-9e4e-11e4-8f69-3f1bf18fe6cb.png)

<h6>How To</h6>: 

Open your Info.plist and add a new Number cell with name <b>CVCalendarStarterWeekday</b>. Then set the appropriate value. Note, that the minimal value is 1 and the maximal is 7. (Sunday ... Saturday).

![2015-01-17 13 43 53](https://cloud.githubusercontent.com/assets/6762769/5789942/321b16d2-9e4f-11e4-954a-cd04d950ae10.png)

**Comment by tiemevanveen** [comment]
Yeah you can close the issue, all working now. Thanks again! 

![img_5063](https://cloud.githubusercontent.com/assets/1330668/5790170/c5c35fec-9e8c-11e4-9d92-6a3dfd2c5481.PNG)

**Comment by Mozharovsky** [comment]
I hope your app is gonna be amazing one! :+1:

**Comment by awaisjee15** [comment]
hi Mozharovsky,
i want to add  "NSCalendarIdentifierPersian" in updated cvcalendar but .i 'm failed to find where i have change .can you please help me.thanks

**Comment by mustoceacatalin** [comment]
Hi. I'm trying to integrate this calendar in an app, I fallowed all the steps, and imported the library, but the calendar doesn't show on my view, it remains blank, and when I am trying to click a button from the view i get this error: 'fatal error: unexpectedly found nil while unwrapping an Optional value'. Do you have any ideas? Thanks!
![screen shot 2016-04-06 at 15 35 30](https://cloud.githubusercontent.com/assets/12028287/14316922/5d78b3e8-fc0e-11e5-9e90-7f5ced027483.png)

**Comment by neugartf** [comment]
Have you set your view class to CVCalendarView and created an IBOutlet?

**Comment by mustoceacatalin** [comment]
thanks very much, that was the problem. It looks amazing!
